syntax = "proto3";

option csharp_namespace = "nerv.log";

import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";

service LogIngestionService {
  rpc StreamLogs(stream LogRequest) returns (IngestionResponse);
}

enum LogLevel {
  LOG_LEVEL_UNSPECIFIED = 0;
  LOG_LEVEL_TRACE = 1;
  LOG_LEVEL_DEBUG = 2;
  LOG_LEVEL_INFO = 3;
  LOG_LEVEL_WARNING = 4;
  LOG_LEVEL_ERROR = 5;
  LOG_LEVEL_CRITICAL = 6;
}

message LogRequest {
  google.protobuf.Timestamp timestamp = 1;
  
  LogLevel level = 2;
  
  string service_name = 3;
  
  string message = 4;
  
  string environment = 5;

  google.protobuf.Struct metadata = 6;
}

message IngestionResponse {
  bool success = 1;
  int64 logs_processed = 2;
  string message = 3;
}