<Project Sdk="Aspire.AppHost.Sdk/13.4.5">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>f1b7ce08-f474-4a48-ad03-455bbcb4cd05</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.5" />
      <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.4.5" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\nerv.log.Server\nerv.log.Server.csproj" />
    </ItemGroup>

</Project>
